### ISSUE TITLE
Problem running AccountSummaryExample

### ISSUE THREAD

**Issue by ladidalimey** [softwarespartan/IB4m#131]
Hi, I have Matlab v R2019a and am using latest IB Gateway.

I get the following message...

>> AccountSummaryExample
added interface method: TWSNotification
notification listener has been added
Server Version:76
TWS Time at connection:20210628 11:25:57 British Summer Time
Undefined function or variable 'reqAccountSummary'.

Error in AccountSummaryExample (line 51)
session.eClientSocket.reqAccountSummary(0,'All',attrkeys);  pause(1);
 
Exception in thread "EReader": java.lang.AbstractMethodError: com.tws.Handler.orderStatus(ILjava/lang/String;IIDIIDILjava/lang/String;)V
	at com.ib.client.EReader.processMsg(EReader.java:251)
	at com.ib.client.EReader.run(EReader.java:70)

Please can you help.

Thanks

**Comment by softwarespartan** [comment]
Thanks for asking.  Can you try “older” version of TWS/gateway?  Also please send output of “ver” command.  Might just be new/most latest version of TWS might need update api version in IB4m.

**Comment by Despair2000** [comment]
I'm using Gateway 983 and everything works fine.

**Comment by ladidalimey** [comment]
I've tried gateway v972,978 & 981.  Still getting the same issue.

My ver results are:
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.6.0.1472908 (R2019a) Update 9
MATLAB License Number: 40841471
Operating System: Microsoft Windows 10 Home Version 10.0 (Build 19042)
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.6         (R2019a)
Financial Toolbox                                     Version 5.13        (R2019a)
Optimization Toolbox                                  Version 8.3         (R2019a)
Statistics and Machine Learning Toolbox               Version 11.5        (R2019a)
>> 

Thanks.
