### ISSUE TITLE
ghost java folder at startup

### ISSUE THREAD

**Issue by giovannetti87** [softwarespartan/IB4m#140]
Hi all,

I am trying to delve deeper into the link between Java and Matlab in order to understand why scripts execution in my machine becomes increasingly slow and clogged as I let data being collected. I noticed this problem particularly happens during US market normal hours, forcing me to use only 20-30 data-stream. Outside market hour I can generally saturate the whole 100 lines endowment. 
The problem is manifested by an increasingly slowing processing time. When I try to terminate execution of a script by pressing CTRL+C,  I am returned several java-related strings and the script does not actually stop. 

A further issue which happens is that every now and then I have some minor anomaly in loading load TWS973.jar , For example, I may receive the following:
```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: \Users\abelbrown\Dropbox\finance\matlab\IB4m\logs\log.txt (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:290)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:164)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:216)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:257)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:133)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:97)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:689)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:647)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:544)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:440)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:334)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:342)
log4j:ERROR Either File or DatePattern options are not set for appender [FILE].
```

I was wondering, is there a way to control for this?

Thanks,

**Comment by giovannetti87** [comment]
Thanks to @softwarespartan this one got quickly fixed, link here:
https://github.com/softwarespartan/IB4m/issues/139#issuecomment-932191218
