### ISSUE TITLE
WHATIF-order causes disconnect

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#143]
@softwarespartan 

Hi Abel,

I stumbled over a strange problem and think the problem might be within IB4m.

It happens me annoyingly often that directly directly after sending a WHATIF-order I get an error 511 or 512 "Oder Sending Error" - Java exception. And then I'm disconnected from the TWS. This happens more often when there are several AP calls in a row but it also happened when there was no call before some time.

I think The full codes I saw were 249 512 (this I'm sure of) and 21 511 (not so sure on the 21).

Now I tried to look into this a little bit and found, "error codes 511 and 512 (and other 5xx codes) are used in the Java and C# APIs and are client side errors. In other words, they get raised locally in the client when an API request caused an exception. These error codes do not come from TWS.
(...) In any case, 5xx errors indicate that something happened when the client was writing bytes into the socket that it uses to communicate with TWS."

Maybe I should add that I used WHATIF-orders for some time on my live account without problems. It was now when I started a new project and tried it on the paper account that I ran into this problem.

Do you have anything smart to say to this problem? :-)

**Comment by Despair2000** [comment]
@softwarespartan @abelatnvidia

This problem is very hard to grab since it is hard to reproduce. One week ago (when I wrote the initial post) I was really plagued by it and my program exited countless times (surely 15-20 times). Friday I ran the exact same program again and it happened only once that the error occurred. So I assume it depends on what else is going on on the computer (especially java related).

Would be awesome if you would find the time to have a look Abel!

Thanks in advance!

**Comment by softwarespartan** [comment]
Apologies this was missed.  Likely overdue for an IB API update.  This is probably a bug in the API itself.  I should have some time over next few weeks to refresh.  

-Abel

**Comment by Despair2000** [comment]
Now I got a new variation. God knows what caused it:

2 510 Request Market Data Sending Error - java.lang.NullpointerException

And disconnected.

**Comment by Despair2000** [comment]
Happy new year @softwarespartan @abelatnvidia,

Around new year IB send out emails and asked to upgrade to a newer version of TWS (or API?) because of some sort of vulnerability (you maybe also got this email). I was already worried that IB4m maybe won't work afterwards (I think to remember that 29th dec was the date) but so far it still works.
I'm always little confused about API-version vs TWS version. If I understand it right IB4m is still based on the 973 API (?) while the latest TWS version is already 1012. What does this mean? The newer TWS versions are apparently backwards compatible with the older API versions  but we can't use functionality that came with the newer API versions?

On this note, have you been able to think a little bit about the update you named? The disconnections are still bugging me.

**Comment by Despair2000** [comment]
I can add the following info.

1.) The error occurs also on the live account and not only on the paper account.
2.) I think (I'm not 100% but pretty sure) the error so far occurred only when placing a WHATIF-order for options that expire the same day.

**Comment by softwarespartan** [comment]
@Despair2000 I have added latest IB-API updates to IB4m.  You can try these updates out by adding the `tws-101201.jar` file.  There are many IB-API updates to watch out for -- IB has been actively developing the API.   Let me know if this update resolves your disconnect issue.  Also don't hesitate to let me know if you find any bugs.  Cheers!

**Comment by softwarespartan** [comment]
@Despair2000 p.s. apologies this took so long to get rolling, we just welcomed our new baby boy a few weeks ago so it has been a busy time :)

**Comment by Despair2000** [comment]
Congratulations! My son just turned 1 so I know what you are talking about :-)

I will test your update and come with feedback.

**Comment by Despair2000** [comment]
I just tried a first time to connect with the new jar-file and got the following error:

Unrecognized function or variable 'getEventWithRemove'.

Error in TWS.processNotification (line 4)
    event = getEventWithRemove(getSource(n),n.uuid);

Error in connectIB (line 29)
    eConnect(session.eClientSocket,IP,port,clientID); pause(0.5)
 
com.mathworks.jmi.MatlabException: Undefined function 'getEventWithRemove' for input arguments of type 'com.tws.Handler'.
	at com.mathworks.jmi.NativeMatlab.SendMatlabMessage(Native Method)
	at com.mathworks.jmi.NativeMatlab.sendMatlabMessage(NativeMatlab.java:273)
	at com.mathworks.jmi.MatlabLooper.sendMatlabMessage(MatlabLooper.java:120)
	at com.mathworks.jmi.Matlab.mtFevalConsoleOutput(Matlab.java:1835)
	at com.proxy.ProxyBuilder$Handler$2.run(ProxyBuilder.java:127)

**Comment by Despair2000** [comment]
I now change line 4 of the process notification to:

event = getEvent(getSource(n),n.uuid);

After doing this the above error doesn't show up but I can't connect anyway because I get the following error:

-1 502 Couldn't connect to TWS. Confirm that "Enable ActiveX and Socket Clients" is enabled and connection port is the same as "Socket Port" on the TWS "Edit->Global Configuration...->API->Settings" menu. Live Trading ports: TWS: 7496; IB Gateway: 4001. Simulated Trading ports for new installations of version 954.1 or newer: TWS: 7497; IB Gateway: 4002

I receive this although all the mentioned settings are correct and work fine with the TWS973.jar. I tried on two computers and it's the same on both.
After changing back to the old jar-file I can connect as usual. So something seems to be wrong.

**Comment by Despair2000** [comment]
...or am I missing something here now? To use the new jar-file one just have to change it on the javaclasspath, right? Or are there some more changes I should have done?

**Comment by softwarespartan** [comment]
@Despair2000 can you check which version of Matlab and TWS you are using?  My first few thoughts are that this update uses the bleeding edge IB API so might need most recent version of TWS.  Typically, error 502 is a socket issue.  I know the old JAR file works for you but, I would just double check/confirm that you are indeed connecting on a port that is valid for live trading, vs paper trading, vs gateway, etc.  

RE: `getEvent`, apologies this was an src merge bug.  I pushed updated jar that should resolve this.

**Comment by Despair2000** [comment]
I use Matlab 2021b and also the latest TWS (10.12.2j).

I just tried again with the jar-file you uploaded and I get the same error. When you tell me to double check the ports and so on I don't really know what you mean. When I switch to the new jar-file the only think I change is the entry in the javaclasspass. The function I use to connect with the port and IP and the settings of the TWS I don't touch. 

P.S.: The"getEvent-error" is now gone with the new jar-file.

**Comment by Despair2000** [comment]
I really tried everything I could imagine but I can not establish a connection with the new jar-file. I tried with the TWS and gateway (both live and paper), both on PC and MAC. :-(

Can you login with the new jar-file?

**Comment by Despair2000** [comment]
@softwarespartan I haven't made any progress here and have no idea how I can make the new jar-file work. :-(

**Comment by softwarespartan** [comment]
Apologies for delay!  Is it possible to send a log file or any diagnostic info ? For example, even if TWS was not even open, would generate the same error.

**Comment by Despair2000** [comment]
I was just thinking myself about activating the log-file. I have never used the log-file before and obviously I'm doing something wrong. I activated the API-logging in the global configuration of the TWS and as google tells me there should be created a log.txt in the installation directory of the TWS. Sadly this is not the case. There is a file called launcher.log but this seems to be only logging the login to the TWS.

However the same error is thrown if the TWS isn't even running. So I'm not sure if there would be something in the log-file if I could find it :-/

So you can login with this jar-file?

**Comment by Despair2000** [comment]
Now I managed to capture some log. This is from the gateway. There you can view the log (and use copy/paste). I still have not managed getting the whole log-file. However the following pops up in the log file when I try to connect:


2022-02-19 15:36:58.870 [SN] INFO  [JTS-CCPDispatcherS2-35] - Setting time offset to -870 diff -128
2022-02-19 15:36:58.870 [SN] INFO  [JTS-CCPDispatcherS2-35] - CCP reported time: 2022-02-19 14:36:58.000 (GMT) [1645281418000], local time: 2022-02-19 14:36:58.870 (GMT), local time: 2022-02-19 15:36:58.870 (CET), difference in seconds: -0.870, handling delta:0 [Msg1]
2022-02-19 15:37:20.277 [SN] INFO  [JTS-Cleaner-34] - market data wrapper, cleaning maps
2022-02-19 15:37:38.996 [SN] INFO  [JTS-CCPDispatcherS2-35] - Setting time offset to -996 diff -126
2022-02-19 15:37:38.996 [SN] INFO  [JTS-CCPDispatcherS2-35] - CCP reported time: 2022-02-19 14:37:38.000 (GMT) [1645281458000], local time: 2022-02-19 14:37:38.996 (GMT), local time: 2022-02-19 15:37:38.996 (CET), difference in seconds: -0.996, handling delta:0 [Msg1]
2022-02-19 15:37:47.888 [SN] INFO  [JTS-SocketListener-52] - State: HEADER, IsAPI: UNKNOWN
2022-02-19 15:37:47.888 [SN] INFO  [JTS-SocketListener-52] - State: STOP, IsAPI: YES
2022-02-19 15:37:47.888 [SN] INFO  [JTS-SocketListener-52] - The following API connection flags are allowed: [PACEAPI]
2022-02-19 15:37:47.888 [SN] INFO  [JTS-SocketListener-52] - ArEServer: Adding 1896038440 with id 2147483647
2022-02-19 15:37:47.888 [SN] INFO  [JTS-SocketListener-52] - eServersChanged: 1
2022-02-19 15:37:47.889 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:SYS] Starting new conversation with client on 127.0.0.1
2022-02-19 15:37:47.889 [SN] INFO  [JTS-EServerSocketNotifier-103] - Starting async queue thread
2022-02-19 15:37:47.890 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:SYS] Server version is 165
2022-02-19 15:37:47.890 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:SYS] Client version is 165
2022-02-19 15:37:47.890 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:SYS] is 3rdParty true
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:INFO] Start processing incoming messages for client {2147483647} using pacer.
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:INFO] Handling incoming StartApi(71) message.
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:DET] Started reading message:
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:DET] Finished reading message:
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:DET] StartApi(71)::[version=2]
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:DET] [2;0;null]
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:ERR] Socket connection for client{2147483647} has closed. 
2022-02-19 15:37:47.891 [SN] INFO  [JTS-EServerSocket-102] - Connection terminated
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EMsgPacer-105] - [2147483647:165:165:1:0:0:0:DET] Start validating message:
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EMsgPacer-105] - [2147483647:165:165:1:0:0:0:DET] Finished validating message:
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EServerSocket-102] - [2147483647:165:165:1:0:0:0:INFO] Stopped processing incoming messages for client{2147483647}.
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EMsgPacer-105] - [2147483647:165:165:1:0:0:0:DET] Started processing message:
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EServerSocket-102] - [0:165:165:1:0:0:0:INFO] Close call made for client{0} socket connection.
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EServerSocketNotifier-103] - Terminating async queue thread
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EServerSocket-102] - Cleaning up [serverId: 0]...
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EServerSocket-102] - Cleaning up [serverId: 0]...
2022-02-19 15:37:47.892 [SN] INFO  [JTS-EServerSocket-102] - Cleaning up [serverId: 0]...
2022-02-19 15:37:47.893 [SN] INFO  [JTS-EWriter3-104] - [0:165:165:1:0:0:0:INFO] Client{0} already closing or closed.
2022-02-19 15:37:47.893 [SN] INFO  [JTS-EMsgPacer-105] - [0:165:165:1:0:15:1:INFO] Sending list of managed accounts.
2022-02-19 15:37:47.906 [SN] INFO  [JTS-EMsgPacer-105] - [0:165:165:1:0:15:1:DET] [15;1;U7339779]
2022-02-19 15:37:47.906 [SN] INFO  [JTS-EMsgPacer-105] - [0:165:165:1:0:9:1:INFO] Sending next valid order id.
2022-02-19 15:37:47.906 [SN] INFO  [JTS-EMsgPacer-105] - [0:165:165:1:0:9:1:DET] [9;1;22]
2022-02-19 15:37:47.906 [SN] INFO  [JTS-EWriter3-104] - [0:165:165:1:0:0:0:SYS] Writer thread terminated for socket client{0}.
2022-02-19 15:37:47.906 [SN] INFO  [JTS-EMsgPacer-105] - [0:165:165:1:0:0:0:DET] Finished processing message:
2022-02-19 15:37:47.906 [SN] INFO  [JTS-EServerSocket-102] - [0:165:165:1:0:0:0:DET] closePrim called.  Stopping all mkt data and HMDS requests for client{0}.
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - ArEServer: Removing 1896038440 with id 0
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - eServersChanged: 0
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - ============ EServerSocket messages stats ============
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - Number of socket messages pushed to updates queue: 0
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - Number of socket messages sent directly: 3
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - =======================================================
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - [0:165:165:1:0:0:0:INFO] Closed API client{0} session.
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - There are no API orders being processed.
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - SecDefRequestTimeOut: There are no timed out SecDef requests.
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - UnhandledOrderPresetRequest: There are no unprocessed order preset requests.
2022-02-19 15:37:47.907 [SN] INFO  [JTS-EServerSocket-102] - [0:165:165:1:0:0:0:SYS] Ending conversation with client{0} at 127.0.0.1
2022-02-19 15:37:55.440 [SN] INFO  [AWT-EventQueue-1] - Parent for Dialog is not isAlwaysOnTop: jclient.logging.q[,165,307,811x466,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=View Logs,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,811x466,layout=jtscomponents.plaf.ac,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-02-19 15:37:55.442 [SN] INFO  [AWT-EventQueue-1] - Parent for Dialog is not isAlwaysOnTop: jclient.logging.q[,165,307,811x466,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=View Logs,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,811x466,layout=jtscomponents.plaf.ac,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]

**Comment by Despair2000** [comment]
Now I found at least also the logs in the TWS.
I will try to provide tomorrow more logs of what is going on. I looked over it but there was nothing that caught my intention. Then I don't really know what to look for either.

**Comment by Despair2000** [comment]
So I now tried again after I found the logs in the TWS and when I attempt to login with IB4m there isn't logged anything (almost). This is although I activated detailed logging. Obviously the log I posted yesterday showed a lot of other things that did not belong to my login attempt.
I now started the TWS and tried to login twice with the API. The following was logged:

============================== Log file: /Users/boriskleine/Jts/milbcblkagmloocjldnbedbojialplcealbooiaf/api.0.20220220.100521.ibgzenc =============================
10:05:21:715 -> --- 15-1-DUXXXXXXX-
10:05:21:720 -> --- 9-1-1-

============================== Log file: /Users/boriskleine/Jts/milbcblkagmloocjldnbedbojialplcealbooiaf/api.0.20220220.100549.ibgzenc =============================
10:05:49:263 -> --- 15-1-DUXXXXXXX-
10:05:49:266 -> --- 9-1-1-

**Comment by Despair2000** [comment]
I understand that you are busy with other issues. Just drop a line when we can investigated this issue further (I did not make any progress). I will so long keep on using the 973 jar-file.

**Comment by Despair2000** [comment]
@softwarespartan
Hi Abel,
I'm still using here the old jar-file. Any chance that we can look at this problem?
