### ISSUE TITLE
session.eClientSocket.reqPositions() causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by Despair2000** [softwarespartan/IB4m#42]
Hi Abel,

I experience an issue that seems similar to an issue another user reported about 1 year ago (issue #15). In this thread one can read that you resolved the issue but somehow it is still there.

For me requesting open position when there is none throws the following error:

Exception in thread "Thread-27": java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.tws.Handler.processEvent(Handler.java:368)
	at com.tws.Handler.positionEnd(Handler.java:538)
	at com.ib.client.EDecoder.processPositionEndMsg(EDecoder.java:1918)
	at com.ib.client.EDecoder.processMsg(EDecoder.java:183)
	at com.ib.client.EReader.processMsgs(EReader.java:116)
	at com.ib.client.EClientSocket$MessageProcessingThread.run(EClientSocket.java:46)

I'm afterwards not disconnected from TWS like the user described in issue #15.
Requesting open positions when there are one or more works fine.

I'm running the latest versions of everything (TWS, IB4m and matlab 2018b).

This issue is not very severe since the program doesn't stop running on this error but I wanted to report it anyway since I see the error in my log files frequently.

Cheers

**Comment by softwarespartan** [comment]
Thanks for reaching out. Yes, this should be fixed.  I’ll look into it ASAP.
